# Generated by Django 4.1 on 2022-09-14 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0002_rename_products_product"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product", name="image", field=models.URLField(),
        ),
        migrations.AlterField(
            model_name="product", name="price", field=models.CharField(max_length=13),
        ),
    ]
